### ISSUE TITLE
leaflet map of CorrelAidX chapters

### ISSUE THREAD

**Issue by friep** [CorrelAid/correltools#2]
With the increasing number of CorrelAidX chapters, it would be nice to have a map to display them geographically. 

For this, create a leaflet map and save it as a html widget so that it can be embedded on our website on the CorrelAidX page. 

cf: https://waterdata.usgs.gov/blog/leaflet/

additionally, we should store the CorrelAidX data as part of the package and provide functions that make it easy to add new chapter(s).

**Comment by christine-hvw** [comment]
Hi Frie, I started working on this. First draft is in [my Fork](https://github.com/christine-hvw/correltools/tree/issue2-correlaidx-map).

**Comment by friep** [comment]
thanks @christine-hvw 🙏 let me know if you need help!!
