### ISSUE TITLE
Rmarkdown Theme

### ISSUE THREAD

**Issue by jansim** [CorrelAid/correltools#8]
Just an idea, but in line with #1, maybe a custom theme for Rmarkdown reports might be a nice addition?

Some general info on Rmarkdown themes https://bookdown.org/yihui/rmarkdown/html-document.html#appearance_and_style and a gallery of themes https://www.datadreaming.org/post/r-markdown-theme-gallery/

**Comment by friep** [comment]
@jansim funny that i see this now.. i just thought about that yesterday.. :D 

do you have the time to work on that? do you want to collaborate? i have some more free time now that our traditional 'summer break' is coming up

**Comment by jansim** [comment]
I would be more than happy to collaborate on this! Do you already have sth in mind as to how a finished template might look? (this is probably the hardest part 😄) I'd be quite curious to figure out how these templates are actually treated within Rmarkdown / knitr and which files have to go where for them to be recognized properly.

**Comment by friep** [comment]
closed by c2cffc82ad427850ad248b57467d2e92d34fd503 and following commits :)
